### ISSUE TITLE
Build transcript and gene expression matrices

### ISSUE THREAD

**Issue by bprabin** [trinityrnaseq/trinityrnaseq#102]
Hi,
I have kallisto output files. I use the following script to build transcript and gene expression matrices and get a error..
prabinb@biolab:~> /data/trinityrnaseq-2.1.1/util/abundance_estimates_to_matrix.pl --est_method kallisto --out_prefix trans_kcounts --name_sample_by_basedir /data/Prabin_trinity/abundance.tsv 
-reading file: target_id	length	eff_length	est_counts	tpm
Error, cannot open file target_id	length	eff_length	est_counts	tpm at /data/trinityrnaseq-2.1.1/util/abundance_estimates_to_matrix.pl line 153.

Any solution for this please...

**Comment by brianjohnhaas** [comment]
Hi - sorry for the delay!  most user requests come in through the google group:
https://groups.google.com/forum/#!forum/trinityrnaseq-users

In the case of this error, you need to specify multiple input files for generating the matrix. Because only one input was given, it assumed that file contained a list of all the files to explore for building the matrix. I'll update the usage info for this script.
