### ISSUE TITLE
Spaces in fastq header lines cause names to truncate

### ISSUE THREAD

**Issue by benfulton** [trinityrnaseq/trinityrnaseq#3]
If there is a space in the fastq header lines, then Trinity will truncate the name at that space and add /H. This was a problem in analyzing a dual stranded data set and trinity lost the /1 or /2 that was at the end of each header.

After Chrysalis finishes using bowtie the pipeline fails with a series of errors like this:

warning, ignoring read: <read-name>/H since cannot decipher if /1 or /2 of a pair.

Example from Sequence Read Archive:
head all_merged_reads.fq.original
@SRR1270869.97 HWI-ST318:320:C1FH2ACXX:8:1101:7644:2071/1
NTGACTTTCAATAGATCGCAGCGAGGGAGCTGCTCTGCTACGTACGAAAC

Workaround is to remove the space.

**Comment by Perugolate** [comment]
It would be nice to have `Trinity` be a bit more tolerant of the fastq headers (still seeing it in v2.0.6) as it is a bit annoying for SRA data. It seems there is a suggestion in `$TRINITY_HOME/trinityrnaseq/util/misc/SRA_to_fastq.notes` that one should the `--defline-seq '@$sn[_$rn]/$ri'` option to `fastq-dump`. However if one instead always gets .fastq.bz2 from the DDBJ SRA mirror (in order to avoid sra format and fastq-dump) then there is the possibility that the spaces slip through the net only to kill your jobs (that have already queued for ages).

**Comment by brianjohnhaas** [comment]
will add sra-to-trinity documentation, and update the code to recognize when problems are likely to occur.

**Comment by brianjohnhaas** [comment]
I updated fastool so it'll crash early on if it cannot parse the fastq file format.

We added documentation on SRA conversions to the FAQ page.

If there are other formatting issues that continue to arise, we'll deal with them accordingly.  Best we can do for now.
