### ISSUE TITLE
variant_calling

### ISSUE THREAD

**Issue by sofiapar265** [trinityrnaseq/trinityrnaseq#407]
Hi Brian,
   I have a question regarding the output of the variant_calling.py. First, I don't get a Aligned.sortedByCoord.out.bam but only two other .bam files (dedduped.valid.bam and rg_added_sorted.bam). I am a bit confused of which should i use for visualization on IGV. 
One more thing is that I search for SNPs charred among 4 vcf files (4 libraries). Is there a case that I can provide in trinity all the 4 pairs of paired-end reads at the same time in order to get at the end only the shared SNPs (1 vcf file)?
Thanks a lot in advance and I am really sorry for spamming you with so many questions
Best,
Sofia

**Comment by brianjohnhaas** [comment]
Hi Sofia,

The current version of the script just takes a single sample of fastq
files.  I'll work on updating it to process multiple samples and will have
an updated version for you later this week.

I'm surprised you're not finding the file 'Aligned.sortedByCoord.out.bam',
as it's the first output generated by STAR.    The deduped.bam should be
fine for viewing in IGV. It just has the duplicate reads marked, and it's
actually the better file to use for viewing anyway. I"ll update the
documentation on this too.

best,

~b



On Mon, Feb 19, 2018 at 5:38 AM, sofiapar265 <notifications@github.com>
wrote:
>
> Hi Brian,
> I have a question regarding the output of the variant_calling.py. First,
I don't get a Aligned.sortedByCoord.out.bam but only two other .bam files
(dedduped.valid.bam and rg_added_sorted.bam). I am a bit confused of which
should i use for visualization on IGV.
> One more thing is that I search for SNPs charred among 4 vcf files (4
libraries). Is there a case that I can provide in trinity all the 4 pairs
of paired-end reads at the same time in order to get at the end only the
shared SNPs (1 vcf file)?
> Thanks a lot in advance and I am really sorry for spamming you with so
many questions
> Best,
> Sofia
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.




--
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas
