### ISSUE TITLE
In silico read normalization

### ISSUE THREAD

**Issue by awshort** [trinityrnaseq/trinityrnaseq#838]
Hello Dr. Haas, 

This is not so much an issue, but a question. I was wondering, if I am trying to generate a de novo transcriptome for reads from four populations from five treatment conditions. Would it make more sense to normalize the reads for the four populations separately prior to running trinity or just run trinity on all of the reads? I should note that I am trying to think of ways to limit the computing power needed to run trinity while also preserving important transcripts that may be unique to a particular population. 

Thank you for your time, 

Sincerely,

Aidan Short

**Comment by brianjohnhaas** [comment]
Hi Aidan,

The following option (when using the --samples_file parameter) will do the
normalization separately, followed by a final round with the combined
normalized reads.  You could give that a try. I'm not sure it should make a
difference though due to the stochastic sampling of the normalization
process.  It helps with RAM usage, though.  It shouldn't hurt, anyway, if
you want to give it a try, and should alleviate your concerns.

#  --normalize_by_read_set              run normalization separate for each
> pair of fastq files,
> #                                       then one final normalization that
> combines the individual normalized reads.
> #                                       Consider using this if RAM
> limitations are a consideration.
> #



On Wed, May 13, 2020 at 4:43 PM awshort <notifications@github.com> wrote:
>
> Hello Dr. Haas,
>
> This is not so much an issue, but a question. I was wondering, if I am
trying to generate a de novo transcriptome for reads from four populations
from five treatment conditions. Would it make more sense to normalize the
reads for the four populations separately prior to running trinity or just
run trinity on all of the reads? I should note that I am trying to think of
ways to limit the computing power needed to run trinity while also
preserving important transcripts that may be unique to a particular
population.
>
> Thank you for your time,
>
> Sincerely,
>
> Aidan Short
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.



--
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas
