### ISSUE TITLE
The Dockerfile

### ISSUE THREAD

**Issue by sghignone** [trinityrnaseq/trinityrnaseq#969]
HI,
I was exploring the dockerfile, and found that RSEM install is repeated twice, tho slightly different. Can you explain me why?
Cheers,
s.-

**Comment by brianjohnhaas** [comment]
Hi,

It was just because the first one didn't include the

cp convert-sam-for-rsem $BIN

and during the initial build I wanted to resume from a later step in the
build process.  I forgot to remove the earlier installation section before
deploying.  It's not needed, though.  I removed it so it won't be in the
next release (devel branch).

best,

~b


On Wed, Jan 27, 2021 at 5:00 AM Stefano Ghignone <notifications@github.com>
wrote:
>
> HI,
> I was exploring the dockerfile, and found that RSEM install is repeated
twice, tho slightly different. Can you explain me why?
> Cheers,
> s.-
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.



--
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas
